<script setup>
import { ref, onMounted, watch } from 'vue'

const props = defineProps({
  thoughts: { type: Array, required: true },
  logs: { type: Array, required: true },
  running: { type: Boolean, default: false }
})

const emit = defineEmits(['complete'])

const currentText = ref('')
const isCompleted = ref(false)

const simulateTyping = async () => {
  currentText.value = ''
  isCompleted.value = false
  
  for (const thought of props.thoughts) {
    currentText.value = thought
    await new Promise(r => setTimeout(r, 1200)) // Pause to let user read
  }
  
  currentText.value = 'Analysis complete. Generating report...'
  await new Promise(r => setTimeout(r, 800))
  
  isCompleted.value = true
  emit('complete')
}

onMounted(() => {
  if (props.running) simulateTyping()
  else isCompleted.value = true
})

watch(() => props.running, (newVal) => {
  if (newVal) simulateTyping()
})
</script>

<template>
  <div class="story-thoughts" :class="{ 'completed': isCompleted }">
    <div class="thought-bubble animate-fade-in" v-if="!isCompleted && currentText">
      <div class="loader-pulse"></div>
      <p>{{ currentText }}</p>
    </div>
    <div class="thought-summary" v-else-if="isCompleted">
      <span class="line"></span>
      <span class="text">Generated by AI Agent</span>
      <span class="line"></span>
    </div>
  </div>
</template>

<style scoped>
.story-thoughts {
  min-height: 120px;
  display: flex;
  align-items: center;
  justify-content: center;
  transition: all 0.8s ease;
}

.story-thoughts.completed {
  min-height: 60px;
  opacity: 0.6;
}

.thought-bubble {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 16px;
  text-align: center;
}

.thought-bubble p {
  font-size: 20px;
  font-weight: 300;
  color: var(--text-secondary);
  font-style: italic;
  max-width: 500px;
  margin: 0;
  line-height: 1.5;
}

.loader-pulse {
  width: 12px;
  height: 12px;
  background: var(--text-primary);
  border-radius: 50%;
  animation: pulse 2s infinite ease-in-out;
}

@keyframes pulse {
  0% { transform: scale(0.8); opacity: 0.3; }
  50% { transform: scale(1.2); opacity: 0.8; }
  100% { transform: scale(0.8); opacity: 0.3; }
}

.thought-summary {
  display: flex;
  align-items: center;
  gap: 16px;
  width: 100%;
}

.thought-summary .line {
  flex: 1;
  height: 1px;
  background: var(--border-subtle);
}

.thought-summary .text {
  font-family: var(--font-mono);
  font-size: 11px;
  text-transform: uppercase;
  letter-spacing: 0.1em;
  color: var(--text-muted);
}
</style>
